### ISSUE TITLE
Pipeline job will pass instead of failing when using jsonOutput and jsonOutputPath flags

### ISSUE THREAD

**Issue by euanblack** [jonsth131/npm-audit#21]
Steps Taken
1. Installed npm-audit Azure Pipeline extension
2. Added npm-audit to .yaml with the following config: 

```
- task: npm-audit@1
  displayName: 'NPM Audit task'
  inputs:
    path: '$(Build.SourcesDirectory)'
    level: 'high'
    jsonOutput: true
    jsonOutputPath: '$(Pipeline.Workspace)'
```
3. Ran the pipeline

Expected Outcome
The job would fail and print the json output.

Actual Outcome
The job passes as shown in the screenshot below. The json output is created as expected. 

![image](https://github.com/jonsth131/npm-audit/assets/150786903/e6b9706e-1563-4805-804a-e6e6e85a6446)

When using the task without setting the json output flags, it fails as expected, as shown in the screenshot below:

![image](https://github.com/jonsth131/npm-audit/assets/150786903/c8c6b324-d59e-4179-892d-510e017ec913)
